server:
  port: 9998

spring:
  datasource:
    username: teacher_info_db
    password: AiH888
    url: jdbc:mysql://localhost:3306/teacher_info_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

ip: 47.113.150.138

# 文件存储路径
file:
  root-path: /www/wwwroot/TeacherInfoManage/files
  template-file-word: /www/wwwroot/TeacherInfoManage/files/template/TemplateTeacherInfo.docx
  template-file-excel-superadmin: /www/wwwroot/TeacherInfoManage/files/template/superadmin/导入教师账号模板.xlsx # excel模板文件
  template-file-excel-admin: /www/wwwroot/TeacherInfoManage/files/template/admin/导入教师账号模板.xlsx # excel模板文件
  temporary-path: /www/wwwroot/TeacherInfoManage/files/temporary
