spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 512MB
  main:
    allow-circular-references: true # 允许bean的覆盖

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 在映射实体&属性时,将数据库中表名和字段名中的下划线去掉,按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: zw_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto
    type-aliases-package: com.aih.entity

excel:
  file-name: 教师信息表
  import-template-name: 导入教师账号模板

file:
  template-file-word: template/TemplateTeacherInfo.docx  # word模板文件
  template-file-excel-superadmin: template/SuperAdminImport.xlsx # excel模板文件
  template-file-excel-admin: template/AdminImport.xlsx # excel模板文件

default-password: 123456
