server:
  port: 9998

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/teacher_info_manage_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

ip: localhost


# 文件存储路径
file:
  root-path: D:\idea\2023\files   # 根路径
  template-file: D:\idea\2023\files\template\TemplateTeacherInfo.docx # 模板文件
  temporary-path: D:\idea\2023\files\temporary  # 临时目录

