server:
  port: 9998

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/teacher_info_manage_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

ip: localhost

# 文件存储路径
file:
  root-path: D:\idea\2023\files

